# Generated by Django 6.0.5 on 2026-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
