# Generated by Django 6.0.5 on 2026-05-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_task_reminders_enabled_user_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='category',
        ),
    ]
