# Generated by Django 6.0.5 on 2026-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_knowledgebase_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
