# Generated by Django 6.0.5 on 2026-05-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_due_time_task_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
    ]
